name: CI (linting, testing and building)
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      uses: actions/checkout@v3
    - name: Staring Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install modules
      run: npm install
    - name: building app (dev mode)
      run: npm run build:dev
    - name: linting types (ts-lint)
      run: npm run lint:ts
    - name: linting styles (style-lint)
      run: npm run lint:scss
    - name: unit-testing
      run: npm run test:unit