name: CI Pipeline
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "14"
            - name: node modules installing
              run: npm i
            - name: building the project (prod. mode)
              run: npm run build:prod
            - name: linting typescript (ts-lint)
              run: npm run lint:ts
            - name: linting styles (style-lint)
              run: npm run lint:scss
            - name: unit-testing
              run: npm run test:unit
            - name: ui-testing
              run: npm run test:ui
